### PR TITLE
Fixed infinite loop when the view appears

### PR DESCRIPTION
**Pull request by FelixLisczyk**
I've noticed a very high CPU usage when the view appears and found an infinite loop:

```mermaid
graph LR
id1("viewDidLayoutSubviews()")
id2("updateUI()")
id3("view.layoutIfNeeded()")

id1-->id2
id2-->id3
id3-->id1
```

### CODE REVIEW

**Comment by lascic** [comment]
That's a very important issue, thanks a lot for pointing this one out. Unfortunately, I need to call `.layoutIfNeeded` multiple times (e.g. when I change the size of the Split View screen on iPad). With the flag set to `false`, the UI wont be adjusted anymore.

**Comment by FelixLisczyk** [comment]
Thanks, I've fixed this issue. Are there any other instances where you need to update the UI?

**Comment by lascic** [comment]
These would be all instances, thanks. On another note, I suggest moving `needsUIRefresh = true` from `traitCollectionDidChange(_:)` within the scope of `viewWillTransition(to:with:)` and I can merge and close this issue: This fixes the size class change issues in all use cases while preventing an infinite loop on `viewDidLayoutSubviews()`.

``` swift
override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
    super.viewWillTransition(to: size, with: coordinator)
    needsUIRefresh = true
}
```

Your help on this one is much appreciated. This was a critical issue that I completely oversaw while updating the framework for the iPad.

**Comment by FelixLisczyk** [comment]
Sure, I've added the second method. Thanks for merging!

**Pull request merged**
